services:
  jenkins-controller:
    build: ./jenkins-controller
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-keys:/var/jenkins_home/.ssh
    networks:
      - jenkins-network

  jenkins-java-agent:
    build: ./jenkins-java-agent
    container_name: jenkins-java-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-keys:/home/jenkins/.ssh-shared:ro
      - jenkins-cache:/home/jenkins/.m2/repository
      - jenkins-cache:/home/jenkins/.cache/trivy
    networks:
      - jenkins-network
    depends_on:
      - jenkins-controller
networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-keys:
  jenkins-cache: